#ifndef QLAZERDRIVECLIENT_GLOBAL_H
#define QLAZERDRIVECLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QLAZERDRIVECLIENT_LIBRARY)
#  define QLAZERDRIVECLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QLAZERDRIVECLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QLAZERDRIVECLIENT_GLOBAL_H
